// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAK-aPsTL4xu08QjfwYySUVIr0bSqKoNnA',
    appId: '1:604177949133:web:d6aa8690ad28912908e484',
    messagingSenderId: '604177949133',
    projectId: 'immuno-warriors-9e3b1',
    authDomain: 'immuno-warriors-9e3b1.firebaseapp.com',
    storageBucket: 'immuno-warriors-9e3b1.firebasestorage.app',
    measurementId: 'G-HMC8MRJ677',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgrJ2qqnjXp0ibt2_LaHP7KOYXEjW1HUI',
    appId: '1:604177949133:android:43b29340c80ae5a208e484',
    messagingSenderId: '604177949133',
    projectId: 'immuno-warriors-9e3b1',
    storageBucket: 'immuno-warriors-9e3b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUtRPLhDy5A_n2GSr9M2jVDCUARD5gwf0',
    appId: '1:604177949133:ios:ac0d5badd3b7402208e484',
    messagingSenderId: '604177949133',
    projectId: 'immuno-warriors-9e3b1',
    storageBucket: 'immuno-warriors-9e3b1.firebasestorage.app',
    iosClientId: '604177949133-g55u1f22fr868gv6aiu2d21kgih6d9vb.apps.googleusercontent.com',
    iosBundleId: 'com.example.immunoWarriors',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUtRPLhDy5A_n2GSr9M2jVDCUARD5gwf0',
    appId: '1:604177949133:ios:ac0d5badd3b7402208e484',
    messagingSenderId: '604177949133',
    projectId: 'immuno-warriors-9e3b1',
    storageBucket: 'immuno-warriors-9e3b1.firebasestorage.app',
    iosClientId: '604177949133-g55u1f22fr868gv6aiu2d21kgih6d9vb.apps.googleusercontent.com',
    iosBundleId: 'com.example.immunoWarriors',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAK-aPsTL4xu08QjfwYySUVIr0bSqKoNnA',
    appId: '1:604177949133:web:b66b5ccd0d44858c08e484',
    messagingSenderId: '604177949133',
    projectId: 'immuno-warriors-9e3b1',
    authDomain: 'immuno-warriors-9e3b1.firebaseapp.com',
    storageBucket: 'immuno-warriors-9e3b1.firebasestorage.app',
    measurementId: 'G-NSX1YWQKL4',
  );
}
