name: theimmunowarriors
description: Tableau de bord futuriste pour l'application ImmunoWarriors.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0 # Pour les polices Poppins
  animations: ^2.0.7 # Pour les animations fluides

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 # Pour les bonnes pratiques de codage

flutter:
  uses-material-design: true
